name: Compile AutoHotkey Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Scoop
        run: |
          iwr -useb get.scoop.sh | iex

      - name: Install AutoHotkey
        run: |
          scoop install autohotkey

      - name: Create output directory
        run: mkdir -Force out

      - name: Compile AutoHotkey script
        run: |
          AutoHotkey.exe /in "hotkeys.ahk" /out "out\hotkeys.exe" /icon "favicon.ico"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary
          path: out\hotkeys.exe
