name: Compile AutoHotkey Script
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  AHK2EXE_VERSION: v1.1.37.02

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and Extract AutoHotkey
        run: |
          $url = "https://www.autohotkey.com/download/ahk-v2.zip"
          Invoke-WebRequest -Uri $url -OutFile "ahk.zip"
          Expand-Archive -Path "ahk.zip" -DestinationPath "AutoHotkey"
          
      - name: Determine AutoHotkey executable
        run: |
          $ahkExe = if ([Environment]::Is64BitOperatingSystem) { "AutoHotkey64.exe" } else { "AutoHotkey32.exe" }
          echo "AHK_EXE=AutoHotkey\$ahkExe" >> $env:GITHUB_ENV

      - name: Checkout Ahk2Exe repository
        uses: actions/checkout@v3
        with:
          repository: AutoHotkey/Ahk2Exe
          path: Ahk2Exe
          ref: ${{ env.AHK2EXE_VERSION }}

      - name: Create output directory
        run: mkdir out

      - name: Compile AutoHotkey script
        run: |
          & "${{ env.AHK_EXE }}" Ahk2Exe\Ahk2Exe.ahk /in "hotkeys.ahk" /out "out\hotkeys.exe" /icon "favicon.ico"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary
          path: out\hotkeys.exe
