name: Compile AutoHotkey Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  AHK_VERSION: 2.0.18

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Scoop
        uses: actions/cache@v3
        with:
          path: ~/scoop
          key: ${{ runner.os }}-scoop-${{ env.AHK_VERSION }}

      - name: Install Scoop and AutoHotkey
        run: |
          if (!(Test-Path ~/scoop)) {
            iwr -useb get.scoop.sh | iex
          }
          scoop bucket add extras
          scoop install extras/autohotkey@${{ env.AHK_VERSION }}

      - name: Create output directory
        run: mkdir -Force out

      - name: Compile AutoHotkey script
        run: |
          AutoHotkey.exe /in "hotkeys.ahk" /out "out\hotkeys.exe" /icon "favicon.ico"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary
          path: out\hotkeys.exe
